### ISSUE TITLE
gazctl: journals prune-forks

### ISSUE THREAD

**Issue by rupertchen** [LiveRamp/gazette#172]
As an operator, I want to be able to list and/or prune fragments in the backing stores which correspond to "dead end" forks in history and represent some time range or offset range.

These forks commonly occur when gazette pods are deleted and can create a lot of clutter in the cloud storage. An operator may want to explicitly delete clean these up after an on-call issue even though they have not exceeded the configured retention.

- This functionality could be hooked into `gazctl journals prune` so that it automatically removes forked fragments, avoiding the caveat given in its description.

**Comment by jgraettinger** [comment]
Multiple runs of `gazctl journals prune` will also take care of this:
 - The first iteration, a fragment is removed. However, a partly overlapping fragment is not, since it's not in the broker fragment index.
 - The brokers refresh their index. The removed fragment is dropped. However, the overlapped fragment is now included in the index.
 - gazctl journals prune runs again, sees the overlapped fragment, and removes it.

Given that I don't think this is really a problem?

**Comment by rupertchen** [comment]
My concern is the time interval between a prune operation and brokers refreshing their indexes. For some time, reads at an offset could return different results (as opposed to being completely unavailable).

Empirically, it looks like refresh times of single-digit minutes is pretty common in deployments.

 Another way this could be mitigated is for brokers to refuse to serve offsets from fragments that are eligible for pruning; however, I think it's a net positive for operators to be able to delay pruning.

**Comment by jgraettinger** [comment]
>My concern is the time interval between a prune operation and brokers refreshing their indexes. For some time, reads at an offset could return different results (as opposed to being completely unavailable).

I assume you're referring to the notion that for a few minutes, your read response might return a fragment which doesn't exist anymore (and will 404 on attempting to read it), or it might return a fragment that's been uncovered by a prior prune, depending on who you ask. You'll never get _different_ data at the same offset.

If you happen to ask for an offset that's in a prune-able range, and the read happens to work, I just don't see how that's a problem. In practice, we wouldn't expect clients to be reading out of prune-able ranges - that's why they're pruned. On a relative basis the 404's are way more annoying, but also IMO not a big deal and I'm not aware of a clean & simple way to solve that.

**Comment by rupertchen** [comment]
Isn't it possible to get different data in the following scenario?

Fragments and their ranges in decimal:
- F1: 001-005, prunable
- F2: 005-007, prunable but not indexed
- F3: 005-010, prunable
- F4: 010-042, not prunable

I expect that after a prune run, F2 and F4 will remain and F2 will be picked up during the next index refresh. Wouldn't a request for data at 005 now potentially give different results from a request sent before the prune?

**Comment by jgraettinger** [comment]
When attempting a read @ 005, you'll either get:
 - F3 @ 005, which will 404 on attempting to be read.
 - F2 @ 005, which will successfully read; then a follow-up request at 007 would then return F4 @ 010.

After a second round of pruning and sufficient time for the indexes to refresh,  a read @ 005 will return F4 @ 010.

One thing to point out which may assuage your concern, is that the broker _tells_ you when it's giving you back an offset that is different that what you requested, and reads deal with this appropriately. Depending on when you ask, you may or may not get offset jumps from 005 => 010 or 007 => 010. However, the actual byte returned at a specific offset by the broker never changes.

**Comment by rupertchen** [comment]
I follow what you've described, but I must be missing something. I'm still convinced that a request for 005 before any pruning will return F3 @ 005 while the same request after one round of pruning and index refresh will return F2 @ 005.

**Comment by jgraettinger** [comment]
Oh, definitely. Why is that a concern? Both are valid responses.

**Comment by rupertchen** [comment]
This behavior appears to consumers as if the journal's contents has been mutated and that seems odd to me since journals are advertised as immutable.

**Comment by jgraettinger** [comment]
The _bytes_ returned at offsets 005-007 are identical regardless of whether F2, F3, or any other fragment is read from.

Content is immutable. What we're not making guarantees about w/ pruning is _availability_.

**Comment by jgraettinger** [comment]
Closing - please re-open or comment if you still feel this is an issue.
