### ISSUE TITLE
consensus: defensive watch reloads 

### ISSUE THREAD

**Issue by jgraettinger** [LiveRamp/gazette#24]
We've observed a production bug where, during Etcd instability / network partition, the consensus allocator's `RetryWatcher` appears to miss / not receive expiration watch updates from Etcd. The symptoms are that the watcher continues to receive and patch ongoing updates into it's copy of the tree after it re-establishes a connection to Etcd, but a set of keys which have in actuality long-since expired, never have corresponding expiration events received & patched in.

What's odd about this is that the RetryWatcher implementation will perform a full tree reload on basically any kind of error, so this appears to be a fully silent omission (as a surfaced network error or Etcd index error would have triggered a reload).

We need a means to detect that this has happened, and trigger a full reload from Etcd in response to it.

**Comment by jgraettinger** [comment]
Another option: omit trying to detect this state, and instead perform a periodic full refresh (eg, every N minutes). This appears easy, and at least upper-bounds a the time interval impact of an incident.

**Comment by joshk0** [comment]
spoke to Julian and he's game to take this ticket on. He will be following up with you if there are any deep questions about how to test the solution or how the refresh will work.

**Comment by julianvmodesto** [comment]
I'm going with the periodic refreshes for now since the watch error seems undetectable right now.

This looks like the upstream issue: https://github.com/coreos/etcd/issues/8980

It's still affecting the current etcd v3.3 too: https://github.com/coreos/etcd/issues/8980#issuecomment-350070264
> >   As a final note, even with multiple etcds, there can be total connection loss to the etcd cluster (in our case this was caused by some as of yet undiagnosed routing issue affecting only specific kubernetes pods).

> Agree. We will address this in the next release cycle (hopefully v3.4).
Also document the current watch limitations in 3.3 release.

The mentioned fix in v3.4 would be setting a max retry when the watch loses connection instead of retrying forever: https://github.com/coreos/etcd/pull/9016/files#diff-bdef56e462f289cae8e13ebbe16ba455R61
