### ISSUE TITLE
gorocks: update / investigate embedding rocksdb

### ISSUE THREAD

**Issue by jgraettinger** [LiveRamp/gazette#60]
Our gorocks is apparently broken on 18.04 for non-dockerized builds, which is breaking some developer workflows. We'll need to re-pin gorocks and RocksDB itself to unbreak.

While at it, investigate whether we should switch to gorock's embedded build.

**Comment by jgraettinger** [comment]
Also, release `5.14.0` includes the following new feature which is greatly needed for reporting use cases:
 > Introduce TTL for level compaction so that all files older than ttl go through the compaction process to get rid of old data.

We should figure out how to integrated with gorocksdb?

**Comment by evanryanlin** [comment]
Recording our oral conversation for future reference: I looked into embedding rocksdb briefly. Gorocks used to support an embedded rocks build through CockroachDB, but it has been deprecated (https://github.com/tecbot/gorocksdb/commit/1dead1718d5075d6db883a584dc82b748f22c774#diff-04c6e90faac2675aa89e2176d2eec7d8) and gorocks no longer supports any embedded build. CockroachDB now handles rocks versioning by linking to a forked version of rocksdb that they maintain themselves with their own internal release branches. The CockroachDB makefile builds their version of rocks along with the rest of CockroachDB. This approach isn't really feasible for us, it's way too heavyweight. My (quick) search didn't uncover any other major projects that were embedding rocksdb.

Since it doesn't look like there are currently great options for embedding rocks, we'll just upgrade the version and continue linking to rocks dynamically.

**Comment by jgraettinger** [comment]
This is resolved now, right, with https://github.com/LiveRamp/gazette/commit/fc2cf37e674755c1f64cec8f6ed217d2b62f6d06 ? Anything left to do here?

**Comment by evanryanlin** [comment]
Yes, I just forgot to close! Will do now.
