### ISSUE TITLE
fragment flush interval

### ISSUE THREAD

**Issue by adayNU** [LiveRamp/gazette#63]
We want to run a process on gazette fragments which we'd like to have include all fragments from a previous 24hr window (e.g. 12:00:00 AM PT-11:59:59 PM PT).

Today it's difficult to determine when to run the aforementioned process because there is no guarantee as to when a spool created prior to the 24h window will close and upload the remaining events from that window to cloud storage. Especially if there is high variability in the number of writes to the consumed topic, the timing could be highly variable (I believe). Currently the only way to make a guarantee that we have included all fragments from a given window is to read all fragments until we hit one from a timestamp after the window (and perhaps fail our process if no such fragment is read).

The goal would be to have a process (perhaps a cron) which submits a request to the broker to close its current spool (even if said spool is still relatively small) and then upload that spool to cloud storage. This should provide a much easier ability to guarantee we are processing all fragments from a previous time frame.

**Comment by jgraettinger** [comment]
Thanks. Agreed this makes sense. With gazette2 I'm thinking this should be a property of journal configuration, that the user be able to specify an interval of UTC time such that after each interval completes any current non-empty spool will be closed off and uploaded.

**Comment by jgraettinger** [comment]
Implementation sketch: add a new `roll_interval` time.Duration property to the `JournalSpec.Fragment` message. If non-zero, this interval segments UTC time, and the append API should close and roll a current Spool which was opened in a prior UTC time segment than the current time segment.

For example, if `roll_interval` is 6 hours, then time since the unix epoch is divided into 6 hour segments, and any time point can be mapped into its corresponding time segment via integer division (by `roll_interval`). If the spool obtained by the append API was opened in a prior segment than time.Now, it should be rolled.

**Comment by jskelcy** [comment]
Would coupling the `roll_interval` checking logic to the `Append` API not fall prey to the same issue that currently exists. That being that a low write volume journal may see so few calls to `Append` that we do not check the `roll_interval` in a timely fashion. For example, if some batch job waits 6 hours plus 10 minutes (i.e. the above 6 hour example) they may still miss the last 6-hour fragment as the last write to the journal was at 6 hours minus 5 minutes?

**Comment by adayNU** [comment]
A few thoughts here from my assumptions around use:

1) We would likely use a `roll_interval` which is smaller than our "processing interval" (e.g. if we want to process a 24h window of data, we may set the roll interval to 12h or 6h)
2) We assume that we are receiving at least 1 write per minute in each of our use cases (in every case, significantly more than 1 WPS at peaks).
3) Our batch process is set to begin well after the end of the window we hope to scan (e.g. we currently run this process at 3pm the day following).

Again, nothing here provides a strong guarantee that the data is there, but in practice it's virtually impossible (excluding a borked gazette cluster or other catastrophic state) to have it not have been previously rolled.

**Comment by jgraettinger** [comment]
@jskelcy good question. My own thoughts here are that we can provide a tight bound due to the existing journal [maintenceLoop](https://github.com/LiveRamp/gazette/blob/master/v2/pkg/broker/service.go#L60), which is driven every minute and ensures the liveness and health of the journal replication pipeline. Indeed, when this ticket was started, that used to run the full AppendAPI flow. Now, the [checkHealth](https://github.com/LiveRamp/gazette/blob/master/v2/pkg/broker/replica.go#L230) just acquires the replication pipeline and performs a no-op commit.

Sagar & I were looking at having [updateProposal](https://github.com/LiveRamp/gazette/blob/master/v2/pkg/broker/append_api.go#L263) implement this roll-interval check, and I don't see any reason `updateProposal` can't be called from `checkHealth`.

**Comment by jskelcy** [comment]
Got it. I have plenty here to start digging. I will say however that `roll` might be a slightly overloaded term here, I am thinking that we use the term `roll` to talk about rolling spools to new offsets. How would people feel about `flush_interval`?
